-- ============================================================
-- Экономия цемента: фиксация отрицательного остатка силоса
-- при «Обнулить» или «Внести» (пока current < 0).
--
-- КАК ПРИМЕНИТЬ:
--   Supabase Dashboard → SQL Editor → выполнить скрипт целиком.
-- ============================================================

create table if not exists public.warehouse_cement_savings (
  id bigint generated by default as identity primary key,
  silo_id numeric not null,
  amount_kg numeric not null check (amount_kg > 0),
  reason text not null check (reason in ('reset', 'refill')),
  balance_before_tons numeric not null,
  user_name text,
  created_at timestamptz not null default now()
);

create index if not exists warehouse_cement_savings_created_at_idx
  on public.warehouse_cement_savings (created_at desc);

create index if not exists warehouse_cement_savings_silo_created_idx
  on public.warehouse_cement_savings (silo_id, created_at desc);

comment on table public.warehouse_cement_savings is
  'Сэкономленный цемент: |отрицательный остаток| при закрытии цикла силоса (обнуление или внесение).';
comment on column public.warehouse_cement_savings.amount_kg is
  'Экономия в кг (= |current| * 1000 на момент фиксации).';
comment on column public.warehouse_cement_savings.reason is
  'reset — обнуление; refill — внесение при отрицательном остатке.';
comment on column public.warehouse_cement_savings.balance_before_tons is
  'Остаток силоса в тоннах до операции (ожидается ≤ 0).';

-- Обнуление: зафиксировать экономию при минусе, затем current = 0
create or replace function public.warehouse_silo_book_and_reset(
  p_silo_id numeric,
  p_user_name text default null
)
returns table(
  ok boolean,
  error_text text,
  silo_id numeric,
  saving_kg numeric,
  old_current numeric,
  new_current numeric
)
language plpgsql
as $$
declare
  v_old numeric;
  v_saving_tons numeric;
  v_saving_kg numeric;
begin
  if p_silo_id is null or p_silo_id not in (1, 2, 3) then
    ok := false;
    error_text := 'Некорректный силос';
    return next;
    return;
  end if;

  select current into v_old
  from public.warehouse_silos
  where warehouse_silos.silo_id = p_silo_id
  for update;

  if v_old is null then
    ok := false;
    error_text := 'Силос не найден';
    silo_id := p_silo_id;
    return next;
    return;
  end if;

  v_saving_tons := greatest(0, -v_old);
  v_saving_kg := round(v_saving_tons * 1000, 1);

  if v_saving_kg > 0 then
    insert into public.warehouse_cement_savings (
      silo_id, amount_kg, reason, balance_before_tons, user_name
    ) values (
      p_silo_id, v_saving_kg, 'reset', v_old, nullif(trim(p_user_name), '')
    );
  end if;

  update public.warehouse_silos
  set current = 0, updated_at = now()
  where warehouse_silos.silo_id = p_silo_id;

  ok := true;
  error_text := null;
  silo_id := p_silo_id;
  saving_kg := v_saving_kg;
  old_current := v_old;
  new_current := 0;
  return next;
end;
$$;

comment on function public.warehouse_silo_book_and_reset(numeric, text) is
  'Обнуляет силос; при отрицательном остатке пишет экономию в warehouse_cement_savings.';

-- Внесение: при минусе сначала экономия, затем current += delta
create or replace function public.warehouse_silo_book_and_add(
  p_silo_id numeric,
  p_delta_tons numeric,
  p_user_name text default null
)
returns table(
  ok boolean,
  error_text text,
  silo_id numeric,
  saving_kg numeric,
  old_current numeric,
  new_current numeric
)
language plpgsql
as $$
declare
  v_old numeric;
  v_new numeric;
  v_saving_tons numeric;
  v_saving_kg numeric;
begin
  if p_silo_id is null or p_silo_id not in (1, 2, 3) then
    ok := false;
    error_text := 'Некорректный силос';
    return next;
    return;
  end if;

  if p_delta_tons is null or p_delta_tons <= 0 then
    ok := false;
    error_text := 'Количество для внесения должно быть > 0';
    silo_id := p_silo_id;
    return next;
    return;
  end if;

  select current into v_old
  from public.warehouse_silos
  where warehouse_silos.silo_id = p_silo_id
  for update;

  if v_old is null then
    ok := false;
    error_text := 'Силос не найден';
    silo_id := p_silo_id;
    return next;
    return;
  end if;

  v_saving_tons := greatest(0, -v_old);
  v_saving_kg := round(v_saving_tons * 1000, 1);

  if v_saving_kg > 0 then
    insert into public.warehouse_cement_savings (
      silo_id, amount_kg, reason, balance_before_tons, user_name
    ) values (
      p_silo_id, v_saving_kg, 'refill', v_old, nullif(trim(p_user_name), '')
    );
  end if;

  -- Закрыть отрицательный цикл, затем внести (не оставлять минус в остатке)
  v_new := greatest(v_old, 0) + p_delta_tons;

  update public.warehouse_silos
  set current = v_new, updated_at = now()
  where warehouse_silos.silo_id = p_silo_id;

  ok := true;
  error_text := null;
  silo_id := p_silo_id;
  saving_kg := v_saving_kg;
  old_current := v_old;
  new_current := v_new;
  return next;
end;
$$;

comment on function public.warehouse_silo_book_and_add(numeric, numeric, text) is
  'Вносит цемент (>0). При минусе пишет экономию, закрывает цикл (база=0), затем прибавляет поступление.';

-- Проверка
select 'warehouse_cement_savings' as obj, count(*)::text as info
from information_schema.tables
where table_schema = 'public' and table_name = 'warehouse_cement_savings'
union all
select proname, pg_get_function_identity_arguments(oid)
from pg_proc
where pronamespace = 'public'::regnamespace
  and proname in ('warehouse_silo_book_and_reset', 'warehouse_silo_book_and_add');
